packages:
    - cli
    - config/**
    - devtools/**
    - docs
    - engine/**
catalog:
    "@types/node": ^22.14.0
    lint-staged: ^16.1.2
    husky: ^9.1.7
    nuxt: ^3.17.5
    oxlint: ^1.2.0
    typescript: ^5.8.3
    turbo: ^2.5.4
    tsx: ^4.20.6
    vite: ^7.0.6
    vitest: ^3.2.4
    vite-plugin-dts: ^4.5.4
onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@tailwindcss/oxide"
    - better-sqlite3
    - core-js
    - esbuild
    - sharp
    - unrs-resolver
    - vue-demi
