packages:
  - config/**
  - docs
  - engine/**
  - theme
  - testing/**
  - tooling/**

catalog:
  '@types/node': ^22.15.32
  '@vitest/coverage-v8': ^3.2.4
  husky: ^9.1.7
  lint-staged: ^16.1.2
  npm-run-all2: ^8.0.4
  nuxt: ^3.17.5
  oxlint: ^1.2.0
  tsx: ^4.20.6
  turbo: ^2.5.4
  typescript: ^5.8.3
  vite: ^7.0.6
  vite-plugin-dts: ^4.5.4
  vite-plugin-node: ^7.0.0
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
