packages:
    - config/**
    - apps/**
    - engine/**
    - theme
    - testing/**
    - tooling/**

catalog:
    "@styleframe/license": ^2.0.2
    "@types/node": ^22.15.32
    "@vitest/coverage-v8": ^3.2.4
    husky: ^9.1.7
    lint-staged: ^16.1.2
    npm-run-all2: ^8.0.4
    nuxt: ^3.17.5
    oxlint: ^1.2.0
    tsx: ^4.20.6
    turbo: ^2.5.4
    typescript: ^5.8.3
    vite: ^7.0.6
    vite-plugin-dts: ^4.5.4
    vite-plugin-node: ^7.0.0
    vitest: ^3.2.4
    zod: ^4.1.12

catalogs:
    nuxt:
        "@nuxt/content": 3.7.1
        "@nuxt/eslint": 1.9.0
        "@nuxt/image": 1.11.0
        "@nuxt/kit": 4.1.3
        "@nuxt/schema": 4.1.3
        "@nuxt/scripts": 0.11.13
        "@nuxt/test-utils": 3.19.2
        "@nuxt/ui": 4.0.1
        "@nuxtjs/i18n": 10.1.0
        "@nuxtjs/mdc": 0.17.4
        "@nuxtjs/robots": 5.5.5
        "@nuxtjs/sitemap": 7.4.7
        "@nuxtjs/supabase": 2.0.1
        "@supabase/supabase-js": ^2.78.0
        "@vitejs/plugin-vue": ^6.0.1
        "@vue/tsconfig": ^0.8.1
        better-sqlite3: ^12.2.0
        defu: 6.1.4
        nuxt: 4.1.3
        nuxt-llms: 0.1.3
        nuxt-og-image: 5.1.11
        posthog-js: 1.293.0
        tailwindcss: 4.1.17
        vite: npm:rolldown-vite@7.2.5
        vue: ^3.5.24
        vue-tsc: ^3.1.4

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@tailwindcss/oxide"
    - better-sqlite3
    - core-js
    - esbuild
    - sharp
    - unrs-resolver
    - vue-demi
