packages:
  - config/**
  - apps/**
  - engine/**
  - theme
  - testing/**
  - tooling/**

catalog:
  '@microsoft/api-extractor': ^7.58.9
  '@styleframe/license': ^2.0.2
  '@types/node': ^22.19.21
  '@vitest/coverage-v8': ^4.1.8
  husky: ^9.1.7
  jiti: ^2.7.0
  jsdom: ^29.1.1
  lint-staged: ^17.0.7
  npm-run-all2: ^9.0.2
  nuxt: ^3.17.5
  oxlint: ^1.69.0
  tinyglobby: ^0.2.17
  tsx: ^4.22.4
  turbo: ^2.9.18
  typescript: ^5.9.3
  vite: ^8.0.16
  vite-plugin-dts: ^5.0.2
  vite-plugin-node: ^8.0.0
  vitest: ^4.1.8
  zod: ^4.4.3

catalogs:
  nuxt:
    '@nuxt/content': 3.14.0
    '@nuxt/eslint': 1.16.0
    '@nuxt/fonts': 0.14.0
    '@nuxt/image': 1.11.0
    '@nuxt/kit': 4.4.8
    '@nuxt/schema': 4.4.8
    '@nuxt/scripts': 0.11.13
    '@nuxt/test-utils': 3.19.2
    '@nuxt/ui': 4.8.2
    '@nuxtjs/i18n': 10.4.0
    '@nuxtjs/mdc': 0.22.0
    '@nuxtjs/robots': 6.1.1
    '@nuxtjs/sitemap': 8.2.1
    '@nuxtjs/supabase': 2.0.9
    '@supabase/supabase-js': ^2.108.1
    '@vitejs/plugin-vue': ^6.0.7
    '@vue/tsconfig': ^0.9.1
    better-sqlite3: ^12.10.1
    defu: 6.1.7
    nuxt: 4.4.8
    nuxt-llms: 0.2.0
    nuxt-og-image: 6.6.0
    posthog-js: 1.386.6
    tailwindcss: 4.3.1
    vite: ^8.0.16
    vue: ^3.5.38
    vue-tsc: ^3.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
