// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
    import type { Styleframe } from "@styleframe/core";

    /** Returns the global styleframe instance from styleframe.config.ts */
    export function styleframe(): Styleframe;

    export const borderRadiusSwatch: (props?: { variant?: "none" | "sm" | "md" | "lg" | "xl" | "2xl" | "full" }) => string;
    export const borderStyleSwatch: (props?: { variant?: "none" | "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "outset" }) => string;
    export const borderWidthSwatch: (props?: { variant?: "none" | "thin" | "medium" | "thick" }) => string;
    export const boxShadowSwatch: (props?: { variant?: "none" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "inner" | "ring" }) => string;
    export const colorLightnessSwatch: (props?: { variant?: "50" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | "950" }) => string;
    export const colorShadeSwatch: (props?: { variant?: "50" | "100" | "150" | "200" | "base" }) => string;
    export const colorSwatch: (props?: { variant?: "primary" | "secondary" | "success" | "warning" | "danger" | "info" | "light" | "dark" }) => string;
    export const colorTintSwatch: (props?: { variant?: "50" | "100" | "150" | "200" | "base" }) => string;
    export const fontFamilySwatch: (props?: { variant?: "base" | "print" | "mono" }) => string;
    export const fontSizeSwatch: (props?: { variant?: "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" }) => string;
    export const fontWeightSwatch: (props?: { variant?: "extralight" | "light" | "normal" | "medium" | "semibold" | "bold" | "black" }) => string;
    export const letterSpacingSwatch: (props?: { variant?: "tighter" | "tight" | "normal" | "wide" | "wider" }) => string;
    export const lineHeightSwatch: (props?: { variant?: "tight" | "snug" | "normal" | "relaxed" | "loose" }) => string;
    export const spacingSwatch: (props?: { variant?: "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" }) => string;
}

declare module "virtual:styleframe.css" {
    const css: string;
    export default css;
}
