// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
	import type { Styleframe } from "@styleframe/core";

	/** Returns the global styleframe instance from styleframe.config.ts */
	export function styleframe(): Styleframe;
}

declare module "virtual:styleframe.css" {
	const css: string;
	export default css;
}
