import type { Styleframe } from "@styleframe/core";

// Accessibility
import {
	useForcedColorAdjustUtility,
	useNotSrOnlyUtility,
	useSrOnlyUtility,
} from "./accessibility";

// Backgrounds
import {
	useBackgroundAttachmentUtility,
	useBackgroundClipUtility,
	useBackgroundColorUtility,
	useBackgroundImageUtility,
	useBackgroundOriginUtility,
	useBackgroundPositionUtility,
	useBackgroundRepeatUtility,
	useBackgroundSizeUtility,
	useGradientFromUtility,
	useGradientToUtility,
	useGradientViaUtility,
} from "./backgrounds";

// Borders
import {
	useBorderColorBottomUtility,
	useBorderColorEndUtility,
	useBorderColorLeftUtility,
	useBorderColorRightUtility,
	useBorderColorStartUtility,
	useBorderColorTopUtility,
	useBorderColorUtility,
	useBorderColorXUtility,
	useBorderColorYUtility,
	useBorderRadiusBottomLeftUtility,
	useBorderRadiusBottomRightUtility,
	useBorderRadiusBottomUtility,
	useBorderRadiusEndEndUtility,
	useBorderRadiusEndStartUtility,
	useBorderRadiusEndUtility,
	useBorderRadiusLeftUtility,
	useBorderRadiusRightUtility,
	useBorderRadiusStartEndUtility,
	useBorderRadiusStartStartUtility,
	useBorderRadiusStartUtility,
	useBorderRadiusTopLeftUtility,
	useBorderRadiusTopRightUtility,
	useBorderRadiusTopUtility,
	useBorderRadiusUtility,
	useBorderStyleUtility,
	useBorderWidthBottomUtility,
	useBorderWidthEndUtility,
	useBorderWidthLeftUtility,
	useBorderWidthRightUtility,
	useBorderWidthStartUtility,
	useBorderWidthTopUtility,
	useBorderWidthUtility,
	useBorderWidthXUtility,
	useBorderWidthYUtility,
	useDivideColorUtility,
	useDivideStyleUtility,
	useDivideXReverseUtility,
	useDivideXUtility,
	useDivideYReverseUtility,
	useDivideYUtility,
	useOutlineColorUtility,
	useOutlineOffsetUtility,
	useOutlineStyleUtility,
	useOutlineWidthUtility,
	useRingColorUtility,
	useRingInsetUtility,
	useRingOffsetColorUtility,
	useRingOffsetWidthUtility,
	useRingWidthUtility,
} from "./borders";

// Effects
import {
	useBackgroundBlendModeUtility,
	useBoxShadowColorUtility,
	useBoxShadowUtility,
	useMixBlendModeUtility,
	useOpacityUtility,
	useTextShadowColorUtility,
	useTextShadowUtility,
} from "./effects";

// Filters
import {
	useBackdropBlurUtility,
	useBackdropBrightnessUtility,
	useBackdropContrastUtility,
	useBackdropGrayscaleUtility,
	useBackdropHueRotateUtility,
	useBackdropInvertUtility,
	useBackdropOpacityUtility,
	useBackdropSaturateUtility,
	useBackdropSepiaUtility,
	useBlurUtility,
	useBrightnessUtility,
	useContrastUtility,
	useDropShadowUtility,
	useGrayscaleUtility,
	useHueRotateUtility,
	useInvertUtility,
	useSaturateUtility,
	useSepiaUtility,
} from "./filters";

// Flexbox and Grid
import {
	useAlignContentUtility,
	useAlignItemsUtility,
	useAlignSelfUtility,
	useFlexBasisUtility,
	useFlexDirectionUtility,
	useFlexGrowUtility,
	useFlexShrinkUtility,
	useFlexUtility,
	useFlexWrapUtility,
	useGapUtility,
	useGapXUtility,
	useGapYUtility,
	useGridAutoColumnsUtility,
	useGridAutoFlowUtility,
	useGridAutoRowsUtility,
	useGridColumnEndUtility,
	useGridColumnStartUtility,
	useGridColumnUtility,
	useGridRowEndUtility,
	useGridRowStartUtility,
	useGridRowUtility,
	useGridTemplateColumnsUtility,
	useGridTemplateRowsUtility,
	useJustifyContentUtility,
	useJustifyItemsUtility,
	useJustifySelfUtility,
	useOrderUtility,
	usePlaceContentUtility,
	usePlaceItemsUtility,
	usePlaceSelfUtility,
} from "./flexbox-grid";

// Interactivity
import {
	useAccentColorUtility,
	useAppearanceUtility,
	useCaretColorUtility,
	useColorSchemeUtility,
	useCursorUtility,
	usePointerEventsUtility,
	useResizeUtility,
	useScrollBehaviorUtility,
	useScrollMarginBottomUtility,
	useScrollMarginEndUtility,
	useScrollMarginLeftUtility,
	useScrollMarginRightUtility,
	useScrollMarginStartUtility,
	useScrollMarginTopUtility,
	useScrollMarginUtility,
	useScrollMarginXUtility,
	useScrollMarginYUtility,
	useScrollPaddingBottomUtility,
	useScrollPaddingEndUtility,
	useScrollPaddingLeftUtility,
	useScrollPaddingRightUtility,
	useScrollPaddingStartUtility,
	useScrollPaddingTopUtility,
	useScrollPaddingUtility,
	useScrollPaddingXUtility,
	useScrollPaddingYUtility,
	useScrollSnapAlignUtility,
	useScrollSnapStopUtility,
	useScrollSnapTypeUtility,
	useTouchActionUtility,
	useUserSelectUtility,
	useWillChangeUtility,
} from "./interactivity";

// Layout
import {
	useAspectRatioUtility,
	useBottomUtility,
	useBoxDecorationBreakUtility,
	useBoxSizingUtility,
	useBreakAfterUtility,
	useBreakBeforeUtility,
	useBreakInsideUtility,
	useClearUtility,
	useColumnsUtility,
	useDisplayUtility,
	useFloatUtility,
	useInsetEndUtility,
	useInsetStartUtility,
	useInsetUtility,
	useInsetXUtility,
	useInsetYUtility,
	useIsolationUtility,
	useLeftUtility,
	useObjectFitUtility,
	useObjectPositionUtility,
	useOverflowUtility,
	useOverflowXUtility,
	useOverflowYUtility,
	useOverscrollUtility,
	useOverscrollXUtility,
	useOverscrollYUtility,
	usePositionUtility,
	useRightUtility,
	useTopUtility,
	useVisibilityUtility,
	useZIndexUtility,
} from "./layout";

// Sizing
import {
	useHeightUtility,
	useMaxHeightUtility,
	useMaxWidthUtility,
	useMinHeightUtility,
	useMinWidthUtility,
	useSizeUtility,
	useWidthUtility,
} from "./sizing";

// Spacing
import {
	useMarginBlockUtility,
	useMarginBottomUtility,
	useMarginInlineEndUtility,
	useMarginInlineStartUtility,
	useMarginInlineUtility,
	useMarginLeftUtility,
	useMarginRightUtility,
	useMarginTopUtility,
	useMarginUtility,
	useMarginXUtility,
	useMarginYUtility,
	usePaddingBlockUtility,
	usePaddingBottomUtility,
	usePaddingInlineEndUtility,
	usePaddingInlineStartUtility,
	usePaddingInlineUtility,
	usePaddingLeftUtility,
	usePaddingRightUtility,
	usePaddingTopUtility,
	usePaddingUtility,
	usePaddingXUtility,
	usePaddingYUtility,
	useSpaceXReverseUtility,
	useSpaceXUtility,
	useSpaceYReverseUtility,
	useSpaceYUtility,
} from "./spacing";

// SVG
import { useFillUtility, useStrokeUtility, useStrokeWidthUtility } from "./svg";

// Tables
import {
	useBorderCollapseUtility,
	useBorderSpacingUtility,
	useBorderSpacingXUtility,
	useBorderSpacingYUtility,
	useCaptionSideUtility,
	useTableLayoutUtility,
} from "./tables";

// Transforms
import {
	useBackfaceVisibilityUtility,
	usePerspectiveOriginUtility,
	usePerspectiveUtility,
	useRotateUtility,
	useRotateXUtility,
	useRotateYUtility,
	useScaleUtility,
	useScaleXUtility,
	useScaleYUtility,
	useSkewXUtility,
	useSkewYUtility,
	useTransformOriginUtility,
	useTransformStyleUtility,
	useTranslateUtility,
	useTranslateXUtility,
	useTranslateYUtility,
	useTranslateZUtility,
} from "./transforms";

// Transitions and Animation
import {
	useAnimationUtility,
	useTransitionBehaviorUtility,
	useTransitionDelayUtility,
	useTransitionDurationUtility,
	useTransitionPropertyUtility,
	useTransitionTimingFunctionUtility,
} from "./transitions-animation";

// Typography
import {
	useColorUtility,
	useContentUtility,
	useFontFamilyUtility,
	useFontSizeUtility,
	useFontSmoothingUtility,
	useFontStretchUtility,
	useFontStyleUtility,
	useFontVariantNumericUtility,
	useFontWeightUtility,
	useHyphensUtility,
	useLetterSpacingUtility,
	useLineClampUtility,
	useLineHeightUtility,
	useListStyleImageUtility,
	useListStylePositionUtility,
	useListStyleTypeUtility,
	useOverflowWrapUtility,
	useTextAlignUtility,
	useTextColorUtility,
	useTextDecorationColorUtility,
	useTextDecorationLineUtility,
	useTextDecorationStyleUtility,
	useTextDecorationThicknessUtility,
	useTextIndentUtility,
	useTextOverflowUtility,
	useTextTransformUtility,
	useTextUnderlineOffsetUtility,
	useTextWrapUtility,
	useVerticalAlignUtility,
	useWhitespaceUtility,
	useWordBreakUtility,
} from "./typography";

/**
 * Register all utility factories with the Styleframe instance and return their creator functions.
 *
 * This function is useful when you want to register all utilities at once for use with recipes.
 * Each utility factory is registered without default values, allowing recipes to automatically
 * generate utility classes based on the values used in recipe declarations.
 *
 * @example
 * ```typescript
 * import { styleframe } from "styleframe";
 * import { useUtilities } from "@styleframe/theme";
 *
 * const s = styleframe();
 * const {
 *   createMarginUtility,
 *   createPaddingUtility,
 *   createDisplayUtility,
 *   // ... all other utilities
 * } = useUtilities(s);
 *
 * // Now you can use the creator functions to define utility values
 * createMarginUtility({ sm: '0.5rem', md: '1rem', lg: '1.5rem' });
 * createPaddingUtility({ sm: '0.5rem', md: '1rem', lg: '1.5rem' });
 *
 * // Or use them in recipes - utilities are already registered
 * s.recipe({
 *   name: 'button',
 *   base: { display: 'flex' },
 *   variants: {
 *     size: {
 *       sm: { padding: '0.5rem' },
 *       md: { padding: '1rem' },
 *     },
 *   },
 * });
 * ```
 */
export function useUtilities(s: Styleframe) {
	return {
		// Accessibility
		createForcedColorAdjustUtility: useForcedColorAdjustUtility(s),
		createNotSrOnlyUtility: useNotSrOnlyUtility(s),
		createSrOnlyUtility: useSrOnlyUtility(s),

		// Backgrounds
		createBackgroundAttachmentUtility: useBackgroundAttachmentUtility(s),
		createBackgroundClipUtility: useBackgroundClipUtility(s),
		createBackgroundColorUtility: useBackgroundColorUtility(s),
		createBackgroundImageUtility: useBackgroundImageUtility(s),
		createBackgroundOriginUtility: useBackgroundOriginUtility(s),
		createBackgroundPositionUtility: useBackgroundPositionUtility(s),
		createBackgroundRepeatUtility: useBackgroundRepeatUtility(s),
		createBackgroundSizeUtility: useBackgroundSizeUtility(s),
		createGradientFromUtility: useGradientFromUtility(s),
		createGradientToUtility: useGradientToUtility(s),
		createGradientViaUtility: useGradientViaUtility(s),

		// Borders
		createBorderColorBottomUtility: useBorderColorBottomUtility(s),
		createBorderColorEndUtility: useBorderColorEndUtility(s),
		createBorderColorLeftUtility: useBorderColorLeftUtility(s),
		createBorderColorRightUtility: useBorderColorRightUtility(s),
		createBorderColorStartUtility: useBorderColorStartUtility(s),
		createBorderColorTopUtility: useBorderColorTopUtility(s),
		createBorderColorUtility: useBorderColorUtility(s),
		createBorderColorXUtility: useBorderColorXUtility(s),
		createBorderColorYUtility: useBorderColorYUtility(s),
		createBorderRadiusBottomLeftUtility: useBorderRadiusBottomLeftUtility(s),
		createBorderRadiusBottomRightUtility: useBorderRadiusBottomRightUtility(s),
		createBorderRadiusBottomUtility: useBorderRadiusBottomUtility(s),
		createBorderRadiusEndEndUtility: useBorderRadiusEndEndUtility(s),
		createBorderRadiusEndStartUtility: useBorderRadiusEndStartUtility(s),
		createBorderRadiusEndUtility: useBorderRadiusEndUtility(s),
		createBorderRadiusLeftUtility: useBorderRadiusLeftUtility(s),
		createBorderRadiusRightUtility: useBorderRadiusRightUtility(s),
		createBorderRadiusStartEndUtility: useBorderRadiusStartEndUtility(s),
		createBorderRadiusStartStartUtility: useBorderRadiusStartStartUtility(s),
		createBorderRadiusStartUtility: useBorderRadiusStartUtility(s),
		createBorderRadiusTopLeftUtility: useBorderRadiusTopLeftUtility(s),
		createBorderRadiusTopRightUtility: useBorderRadiusTopRightUtility(s),
		createBorderRadiusTopUtility: useBorderRadiusTopUtility(s),
		createBorderRadiusUtility: useBorderRadiusUtility(s),
		createBorderStyleUtility: useBorderStyleUtility(s),
		createBorderWidthBottomUtility: useBorderWidthBottomUtility(s),
		createBorderWidthEndUtility: useBorderWidthEndUtility(s),
		createBorderWidthLeftUtility: useBorderWidthLeftUtility(s),
		createBorderWidthRightUtility: useBorderWidthRightUtility(s),
		createBorderWidthStartUtility: useBorderWidthStartUtility(s),
		createBorderWidthTopUtility: useBorderWidthTopUtility(s),
		createBorderWidthUtility: useBorderWidthUtility(s),
		createBorderWidthXUtility: useBorderWidthXUtility(s),
		createBorderWidthYUtility: useBorderWidthYUtility(s),
		createDivideColorUtility: useDivideColorUtility(s),
		createDivideStyleUtility: useDivideStyleUtility(s),
		createDivideXReverseUtility: useDivideXReverseUtility(s),
		createDivideXUtility: useDivideXUtility(s),
		createDivideYReverseUtility: useDivideYReverseUtility(s),
		createDivideYUtility: useDivideYUtility(s),
		createOutlineColorUtility: useOutlineColorUtility(s),
		createOutlineOffsetUtility: useOutlineOffsetUtility(s),
		createOutlineStyleUtility: useOutlineStyleUtility(s),
		createOutlineWidthUtility: useOutlineWidthUtility(s),
		createRingColorUtility: useRingColorUtility(s),
		createRingInsetUtility: useRingInsetUtility(s),
		createRingOffsetColorUtility: useRingOffsetColorUtility(s),
		createRingOffsetWidthUtility: useRingOffsetWidthUtility(s),
		createRingWidthUtility: useRingWidthUtility(s),

		// Effects
		createBackgroundBlendModeUtility: useBackgroundBlendModeUtility(s),
		createBoxShadowColorUtility: useBoxShadowColorUtility(s),
		createBoxShadowUtility: useBoxShadowUtility(s),
		createMixBlendModeUtility: useMixBlendModeUtility(s),
		createOpacityUtility: useOpacityUtility(s),
		createTextShadowColorUtility: useTextShadowColorUtility(s),
		createTextShadowUtility: useTextShadowUtility(s),

		// Filters
		createBackdropBlurUtility: useBackdropBlurUtility(s),
		createBackdropBrightnessUtility: useBackdropBrightnessUtility(s),
		createBackdropContrastUtility: useBackdropContrastUtility(s),
		createBackdropGrayscaleUtility: useBackdropGrayscaleUtility(s),
		createBackdropHueRotateUtility: useBackdropHueRotateUtility(s),
		createBackdropInvertUtility: useBackdropInvertUtility(s),
		createBackdropOpacityUtility: useBackdropOpacityUtility(s),
		createBackdropSaturateUtility: useBackdropSaturateUtility(s),
		createBackdropSepiaUtility: useBackdropSepiaUtility(s),
		createBlurUtility: useBlurUtility(s),
		createBrightnessUtility: useBrightnessUtility(s),
		createContrastUtility: useContrastUtility(s),
		createDropShadowUtility: useDropShadowUtility(s),
		createGrayscaleUtility: useGrayscaleUtility(s),
		createHueRotateUtility: useHueRotateUtility(s),
		createInvertUtility: useInvertUtility(s),
		createSaturateUtility: useSaturateUtility(s),
		createSepiaUtility: useSepiaUtility(s),

		// Flexbox and Grid
		createAlignContentUtility: useAlignContentUtility(s),
		createAlignItemsUtility: useAlignItemsUtility(s),
		createAlignSelfUtility: useAlignSelfUtility(s),
		createFlexBasisUtility: useFlexBasisUtility(s),
		createFlexDirectionUtility: useFlexDirectionUtility(s),
		createFlexGrowUtility: useFlexGrowUtility(s),
		createFlexShrinkUtility: useFlexShrinkUtility(s),
		createFlexUtility: useFlexUtility(s),
		createFlexWrapUtility: useFlexWrapUtility(s),
		createGapUtility: useGapUtility(s),
		createGapXUtility: useGapXUtility(s),
		createGapYUtility: useGapYUtility(s),
		createGridAutoColumnsUtility: useGridAutoColumnsUtility(s),
		createGridAutoFlowUtility: useGridAutoFlowUtility(s),
		createGridAutoRowsUtility: useGridAutoRowsUtility(s),
		createGridColumnEndUtility: useGridColumnEndUtility(s),
		createGridColumnStartUtility: useGridColumnStartUtility(s),
		createGridColumnUtility: useGridColumnUtility(s),
		createGridRowEndUtility: useGridRowEndUtility(s),
		createGridRowStartUtility: useGridRowStartUtility(s),
		createGridRowUtility: useGridRowUtility(s),
		createGridTemplateColumnsUtility: useGridTemplateColumnsUtility(s),
		createGridTemplateRowsUtility: useGridTemplateRowsUtility(s),
		createJustifyContentUtility: useJustifyContentUtility(s),
		createJustifyItemsUtility: useJustifyItemsUtility(s),
		createJustifySelfUtility: useJustifySelfUtility(s),
		createOrderUtility: useOrderUtility(s),
		createPlaceContentUtility: usePlaceContentUtility(s),
		createPlaceItemsUtility: usePlaceItemsUtility(s),
		createPlaceSelfUtility: usePlaceSelfUtility(s),

		// Interactivity
		createAccentColorUtility: useAccentColorUtility(s),
		createAppearanceUtility: useAppearanceUtility(s),
		createCaretColorUtility: useCaretColorUtility(s),
		createColorSchemeUtility: useColorSchemeUtility(s),
		createCursorUtility: useCursorUtility(s),
		createPointerEventsUtility: usePointerEventsUtility(s),
		createResizeUtility: useResizeUtility(s),
		createScrollBehaviorUtility: useScrollBehaviorUtility(s),
		createScrollMarginBottomUtility: useScrollMarginBottomUtility(s),
		createScrollMarginEndUtility: useScrollMarginEndUtility(s),
		createScrollMarginLeftUtility: useScrollMarginLeftUtility(s),
		createScrollMarginRightUtility: useScrollMarginRightUtility(s),
		createScrollMarginStartUtility: useScrollMarginStartUtility(s),
		createScrollMarginTopUtility: useScrollMarginTopUtility(s),
		createScrollMarginUtility: useScrollMarginUtility(s),
		createScrollMarginXUtility: useScrollMarginXUtility(s),
		createScrollMarginYUtility: useScrollMarginYUtility(s),
		createScrollPaddingBottomUtility: useScrollPaddingBottomUtility(s),
		createScrollPaddingEndUtility: useScrollPaddingEndUtility(s),
		createScrollPaddingLeftUtility: useScrollPaddingLeftUtility(s),
		createScrollPaddingRightUtility: useScrollPaddingRightUtility(s),
		createScrollPaddingStartUtility: useScrollPaddingStartUtility(s),
		createScrollPaddingTopUtility: useScrollPaddingTopUtility(s),
		createScrollPaddingUtility: useScrollPaddingUtility(s),
		createScrollPaddingXUtility: useScrollPaddingXUtility(s),
		createScrollPaddingYUtility: useScrollPaddingYUtility(s),
		createScrollSnapAlignUtility: useScrollSnapAlignUtility(s),
		createScrollSnapStopUtility: useScrollSnapStopUtility(s),
		createScrollSnapTypeUtility: useScrollSnapTypeUtility(s),
		createTouchActionUtility: useTouchActionUtility(s),
		createUserSelectUtility: useUserSelectUtility(s),
		createWillChangeUtility: useWillChangeUtility(s),

		// Layout
		createAspectRatioUtility: useAspectRatioUtility(s),
		createBottomUtility: useBottomUtility(s),
		createBoxDecorationBreakUtility: useBoxDecorationBreakUtility(s),
		createBoxSizingUtility: useBoxSizingUtility(s),
		createBreakAfterUtility: useBreakAfterUtility(s),
		createBreakBeforeUtility: useBreakBeforeUtility(s),
		createBreakInsideUtility: useBreakInsideUtility(s),
		createClearUtility: useClearUtility(s),
		createColumnsUtility: useColumnsUtility(s),
		createDisplayUtility: useDisplayUtility(s),
		createFloatUtility: useFloatUtility(s),
		createInsetEndUtility: useInsetEndUtility(s),
		createInsetStartUtility: useInsetStartUtility(s),
		createInsetUtility: useInsetUtility(s),
		createInsetXUtility: useInsetXUtility(s),
		createInsetYUtility: useInsetYUtility(s),
		createIsolationUtility: useIsolationUtility(s),
		createLeftUtility: useLeftUtility(s),
		createObjectFitUtility: useObjectFitUtility(s),
		createObjectPositionUtility: useObjectPositionUtility(s),
		createOverflowUtility: useOverflowUtility(s),
		createOverflowXUtility: useOverflowXUtility(s),
		createOverflowYUtility: useOverflowYUtility(s),
		createOverscrollUtility: useOverscrollUtility(s),
		createOverscrollXUtility: useOverscrollXUtility(s),
		createOverscrollYUtility: useOverscrollYUtility(s),
		createPositionUtility: usePositionUtility(s),
		createRightUtility: useRightUtility(s),
		createTopUtility: useTopUtility(s),
		createVisibilityUtility: useVisibilityUtility(s),
		createZIndexUtility: useZIndexUtility(s),

		// Sizing
		createHeightUtility: useHeightUtility(s),
		createMaxHeightUtility: useMaxHeightUtility(s),
		createMaxWidthUtility: useMaxWidthUtility(s),
		createMinHeightUtility: useMinHeightUtility(s),
		createMinWidthUtility: useMinWidthUtility(s),
		createSizeUtility: useSizeUtility(s),
		createWidthUtility: useWidthUtility(s),

		// Spacing
		createMarginBlockUtility: useMarginBlockUtility(s),
		createMarginBottomUtility: useMarginBottomUtility(s),
		createMarginInlineEndUtility: useMarginInlineEndUtility(s),
		createMarginInlineStartUtility: useMarginInlineStartUtility(s),
		createMarginInlineUtility: useMarginInlineUtility(s),
		createMarginLeftUtility: useMarginLeftUtility(s),
		createMarginRightUtility: useMarginRightUtility(s),
		createMarginTopUtility: useMarginTopUtility(s),
		createMarginUtility: useMarginUtility(s),
		createMarginXUtility: useMarginXUtility(s),
		createMarginYUtility: useMarginYUtility(s),
		createPaddingBlockUtility: usePaddingBlockUtility(s),
		createPaddingBottomUtility: usePaddingBottomUtility(s),
		createPaddingInlineEndUtility: usePaddingInlineEndUtility(s),
		createPaddingInlineStartUtility: usePaddingInlineStartUtility(s),
		createPaddingInlineUtility: usePaddingInlineUtility(s),
		createPaddingLeftUtility: usePaddingLeftUtility(s),
		createPaddingRightUtility: usePaddingRightUtility(s),
		createPaddingTopUtility: usePaddingTopUtility(s),
		createPaddingUtility: usePaddingUtility(s),
		createPaddingXUtility: usePaddingXUtility(s),
		createPaddingYUtility: usePaddingYUtility(s),
		createSpaceXReverseUtility: useSpaceXReverseUtility(s),
		createSpaceXUtility: useSpaceXUtility(s),
		createSpaceYReverseUtility: useSpaceYReverseUtility(s),
		createSpaceYUtility: useSpaceYUtility(s),

		// SVG
		createFillUtility: useFillUtility(s),
		createStrokeUtility: useStrokeUtility(s),
		createStrokeWidthUtility: useStrokeWidthUtility(s),

		// Tables
		createBorderCollapseUtility: useBorderCollapseUtility(s),
		createBorderSpacingUtility: useBorderSpacingUtility(s),
		createBorderSpacingXUtility: useBorderSpacingXUtility(s),
		createBorderSpacingYUtility: useBorderSpacingYUtility(s),
		createCaptionSideUtility: useCaptionSideUtility(s),
		createTableLayoutUtility: useTableLayoutUtility(s),

		// Transforms
		createBackfaceVisibilityUtility: useBackfaceVisibilityUtility(s),
		createPerspectiveOriginUtility: usePerspectiveOriginUtility(s),
		createPerspectiveUtility: usePerspectiveUtility(s),
		createRotateUtility: useRotateUtility(s),
		createRotateXUtility: useRotateXUtility(s),
		createRotateYUtility: useRotateYUtility(s),
		createScaleUtility: useScaleUtility(s),
		createScaleXUtility: useScaleXUtility(s),
		createScaleYUtility: useScaleYUtility(s),
		createSkewXUtility: useSkewXUtility(s),
		createSkewYUtility: useSkewYUtility(s),
		createTransformOriginUtility: useTransformOriginUtility(s),
		createTransformStyleUtility: useTransformStyleUtility(s),
		createTranslateUtility: useTranslateUtility(s),
		createTranslateXUtility: useTranslateXUtility(s),
		createTranslateYUtility: useTranslateYUtility(s),
		createTranslateZUtility: useTranslateZUtility(s),

		// Transitions and Animation
		createAnimationUtility: useAnimationUtility(s),
		createTransitionBehaviorUtility: useTransitionBehaviorUtility(s),
		createTransitionDelayUtility: useTransitionDelayUtility(s),
		createTransitionDurationUtility: useTransitionDurationUtility(s),
		createTransitionPropertyUtility: useTransitionPropertyUtility(s),
		createTransitionTimingFunctionUtility:
			useTransitionTimingFunctionUtility(s),

		// Typography
		createColorUtility: useColorUtility(s),
		createContentUtility: useContentUtility(s),
		createFontFamilyUtility: useFontFamilyUtility(s),
		createFontSizeUtility: useFontSizeUtility(s),
		createFontSmoothingUtility: useFontSmoothingUtility(s),
		createFontStretchUtility: useFontStretchUtility(s),
		createFontStyleUtility: useFontStyleUtility(s),
		createFontVariantNumericUtility: useFontVariantNumericUtility(s),
		createFontWeightUtility: useFontWeightUtility(s),
		createHyphensUtility: useHyphensUtility(s),
		createLetterSpacingUtility: useLetterSpacingUtility(s),
		createLineClampUtility: useLineClampUtility(s),
		createLineHeightUtility: useLineHeightUtility(s),
		createListStyleImageUtility: useListStyleImageUtility(s),
		createListStylePositionUtility: useListStylePositionUtility(s),
		createListStyleTypeUtility: useListStyleTypeUtility(s),
		createOverflowWrapUtility: useOverflowWrapUtility(s),
		createTextAlignUtility: useTextAlignUtility(s),
		createTextColorUtility: useTextColorUtility(s),
		createTextDecorationColorUtility: useTextDecorationColorUtility(s),
		createTextDecorationLineUtility: useTextDecorationLineUtility(s),
		createTextDecorationStyleUtility: useTextDecorationStyleUtility(s),
		createTextDecorationThicknessUtility: useTextDecorationThicknessUtility(s),
		createTextIndentUtility: useTextIndentUtility(s),
		createTextOverflowUtility: useTextOverflowUtility(s),
		createTextTransformUtility: useTextTransformUtility(s),
		createTextUnderlineOffsetUtility: useTextUnderlineOffsetUtility(s),
		createTextWrapUtility: useTextWrapUtility(s),
		createVerticalAlignUtility: useVerticalAlignUtility(s),
		createWhitespaceUtility: useWhitespaceUtility(s),
		createWordBreakUtility: useWordBreakUtility(s),
	};
}
