/**
 * Standard CSS properties used to validate dynamic utility creation.
 * Organized by category for maintainability.
 */
export const CSS_PROPERTIES: Set<string> = new Set([
	// Display & Box Model
	"display",
	"box-sizing",
	"overflow",
	"overflow-x",
	"overflow-y",
	"overflow-wrap",
	"visibility",
	"opacity",
	"z-index",
	"float",
	"clear",
	"clip",
	"clip-path",

	// Positioning
	"position",
	"top",
	"right",
	"bottom",
	"left",
	"inset",
	"inset-block",
	"inset-block-start",
	"inset-block-end",
	"inset-inline",
	"inset-inline-start",
	"inset-inline-end",

	// Sizing
	"width",
	"height",
	"min-width",
	"min-height",
	"max-width",
	"max-height",
	"inline-size",
	"block-size",
	"min-inline-size",
	"min-block-size",
	"max-inline-size",
	"max-block-size",
	"aspect-ratio",

	// Margin
	"margin",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	"margin-block",
	"margin-block-start",
	"margin-block-end",
	"margin-inline",
	"margin-inline-start",
	"margin-inline-end",

	// Padding
	"padding",
	"padding-top",
	"padding-right",
	"padding-bottom",
	"padding-left",
	"padding-block",
	"padding-block-start",
	"padding-block-end",
	"padding-inline",
	"padding-inline-start",
	"padding-inline-end",

	// Border
	"border",
	"border-top",
	"border-right",
	"border-bottom",
	"border-left",
	"border-width",
	"border-top-width",
	"border-right-width",
	"border-bottom-width",
	"border-left-width",
	"border-style",
	"border-top-style",
	"border-right-style",
	"border-bottom-style",
	"border-left-style",
	"border-color",
	"border-top-color",
	"border-right-color",
	"border-bottom-color",
	"border-left-color",
	"border-radius",
	"border-top-left-radius",
	"border-top-right-radius",
	"border-bottom-right-radius",
	"border-bottom-left-radius",
	"border-collapse",
	"border-spacing",
	"border-image",
	"border-image-source",
	"border-image-slice",
	"border-image-width",
	"border-image-outset",
	"border-image-repeat",
	"border-block",
	"border-block-start",
	"border-block-end",
	"border-block-width",
	"border-block-style",
	"border-block-color",
	"border-block-start-width",
	"border-block-start-style",
	"border-block-start-color",
	"border-block-end-width",
	"border-block-end-style",
	"border-block-end-color",
	"border-inline",
	"border-inline-start",
	"border-inline-end",
	"border-inline-width",
	"border-inline-style",
	"border-inline-color",
	"border-inline-start-width",
	"border-inline-start-style",
	"border-inline-start-color",
	"border-inline-end-width",
	"border-inline-end-style",
	"border-inline-end-color",
	"border-start-start-radius",
	"border-start-end-radius",
	"border-end-start-radius",
	"border-end-end-radius",

	// Outline
	"outline",
	"outline-width",
	"outline-style",
	"outline-color",
	"outline-offset",

	// Background
	"background",
	"background-color",
	"background-image",
	"background-position",
	"background-position-x",
	"background-position-y",
	"background-size",
	"background-repeat",
	"background-origin",
	"background-clip",
	"background-attachment",
	"background-blend-mode",

	// Color
	"color",
	"accent-color",
	"caret-color",
	"color-scheme",
	"forced-color-adjust",
	"print-color-adjust",

	// Typography
	"font",
	"font-family",
	"font-size",
	"font-size-adjust",
	"font-weight",
	"font-style",
	"font-stretch",
	"font-variant",
	"font-variant-caps",
	"font-variant-east-asian",
	"font-variant-ligatures",
	"font-variant-numeric",
	"font-variant-position",
	"font-feature-settings",
	"font-kerning",
	"font-optical-sizing",
	"font-variation-settings",
	"font-synthesis",
	"line-height",
	"letter-spacing",
	"word-spacing",
	"word-break",
	"word-wrap",
	"text-align",
	"text-align-last",
	"text-decoration",
	"text-decoration-color",
	"text-decoration-line",
	"text-decoration-style",
	"text-decoration-thickness",
	"text-decoration-skip-ink",
	"text-underline-offset",
	"text-underline-position",
	"text-transform",
	"text-indent",
	"text-shadow",
	"text-overflow",
	"text-rendering",
	"text-wrap",
	"text-wrap-mode",
	"text-wrap-style",
	"white-space",
	"white-space-collapse",
	"tab-size",
	"hyphens",
	"line-break",
	"hanging-punctuation",
	"writing-mode",
	"direction",
	"unicode-bidi",
	"vertical-align",

	// Flexbox
	"flex",
	"flex-direction",
	"flex-wrap",
	"flex-flow",
	"flex-grow",
	"flex-shrink",
	"flex-basis",
	"justify-content",
	"justify-items",
	"justify-self",
	"align-content",
	"align-items",
	"align-self",
	"order",
	"gap",
	"row-gap",
	"column-gap",
	"place-content",
	"place-items",
	"place-self",

	// Grid
	"grid",
	"grid-template",
	"grid-template-columns",
	"grid-template-rows",
	"grid-template-areas",
	"grid-auto-columns",
	"grid-auto-rows",
	"grid-auto-flow",
	"grid-column",
	"grid-column-start",
	"grid-column-end",
	"grid-row",
	"grid-row-start",
	"grid-row-end",
	"grid-area",

	// Columns
	"columns",
	"column-count",
	"column-width",
	"column-fill",
	"column-rule",
	"column-rule-width",
	"column-rule-style",
	"column-rule-color",
	"column-span",

	// Table
	"table-layout",
	"caption-side",
	"empty-cells",

	// List
	"list-style",
	"list-style-type",
	"list-style-position",
	"list-style-image",

	// Transform
	"transform",
	"transform-origin",
	"transform-style",
	"perspective",
	"perspective-origin",
	"backface-visibility",
	"rotate",
	"scale",
	"translate",

	// Transition
	"transition",
	"transition-property",
	"transition-duration",
	"transition-timing-function",
	"transition-delay",
	"transition-behavior",

	// Animation
	"animation",
	"animation-name",
	"animation-duration",
	"animation-timing-function",
	"animation-delay",
	"animation-iteration-count",
	"animation-direction",
	"animation-fill-mode",
	"animation-play-state",
	"animation-composition",
	"animation-timeline",
	"animation-range",
	"animation-range-start",
	"animation-range-end",

	// Filter & Effects
	"filter",
	"backdrop-filter",
	"mix-blend-mode",
	"isolation",
	"box-shadow",

	// Mask
	"mask",
	"mask-image",
	"mask-mode",
	"mask-position",
	"mask-size",
	"mask-repeat",
	"mask-origin",
	"mask-clip",
	"mask-composite",

	// Scroll
	"scroll-behavior",
	"scroll-margin",
	"scroll-margin-top",
	"scroll-margin-right",
	"scroll-margin-bottom",
	"scroll-margin-left",
	"scroll-margin-block",
	"scroll-margin-block-start",
	"scroll-margin-block-end",
	"scroll-margin-inline",
	"scroll-margin-inline-start",
	"scroll-margin-inline-end",
	"scroll-padding",
	"scroll-padding-top",
	"scroll-padding-right",
	"scroll-padding-bottom",
	"scroll-padding-left",
	"scroll-padding-block",
	"scroll-padding-block-start",
	"scroll-padding-block-end",
	"scroll-padding-inline",
	"scroll-padding-inline-start",
	"scroll-padding-inline-end",
	"scroll-snap-type",
	"scroll-snap-align",
	"scroll-snap-stop",
	"scrollbar-color",
	"scrollbar-gutter",
	"scrollbar-width",
	"overscroll-behavior",
	"overscroll-behavior-x",
	"overscroll-behavior-y",
	"overscroll-behavior-block",
	"overscroll-behavior-inline",

	// Container Queries
	"container",
	"container-name",
	"container-type",

	// Containment
	"contain",
	"contain-intrinsic-size",
	"contain-intrinsic-width",
	"contain-intrinsic-height",
	"contain-intrinsic-block-size",
	"contain-intrinsic-inline-size",
	"content-visibility",

	// Interactivity
	"cursor",
	"pointer-events",
	"touch-action",
	"user-select",
	"resize",

	// Content
	"content",
	"counter-increment",
	"counter-reset",
	"counter-set",
	"quotes",

	// Image
	"object-fit",
	"object-position",
	"image-rendering",
	"image-orientation",

	// Shape
	"shape-outside",
	"shape-margin",
	"shape-image-threshold",

	// Will Change
	"will-change",

	// SVG
	"fill",
	"fill-opacity",
	"fill-rule",
	"stroke",
	"stroke-dasharray",
	"stroke-dashoffset",
	"stroke-linecap",
	"stroke-linejoin",
	"stroke-miterlimit",
	"stroke-opacity",
	"stroke-width",

	// Appearance
	"appearance",

	// Page
	"break-before",
	"break-after",
	"break-inside",
	"page-break-before",
	"page-break-after",
	"page-break-inside",
	"orphans",
	"widows",

	// View Transitions
	"view-transition-name",

	// Anchor Positioning
	"anchor-name",
	"position-anchor",

	// Misc
	"all",
	"box-decoration-break",
]);

export function isKnownCssProperty(name: string): boolean {
	return CSS_PROPERTIES.has(name);
}
