import type { ModifierFactory, Root, UtilityFactory } from "@styleframe/core";
import type { ParsedUtility, UtilityMatch } from "./types";

interface RegistrationEntry {
	factory: UtilityFactory;
	parsed: ParsedUtility;
	/** Each entry is a modifier group from a distinct class usage */
	modifierGroups: (ModifierFactory | ModifierFactory[])[];
}

/**
 * Register utility values detected by the scanner that don't yet exist on the root.
 *
 * For non-arbitrary values, uses the factory's autogenerate function (treating the
 * value key as a token reference). For arbitrary values, registers with the literal
 * CSS value directly.
 *
 * Registration happens via `factory.create(...)` on each matched factory, which is
 * already bound to the `root` that produced the matches via `matchUtilities(parsed, root)`.
 * The `root` parameter is part of the signature to document the mutation target.
 *
 * @param root The Styleframe root that will receive the new utilities
 * @param matches Scanner match results produced from this same root
 * @returns Number of newly registered values
 */
export function registerMatchedUtilities(
	_root: Root,
	matches: UtilityMatch[],
): number {
	const unregistered = matches.filter((m) => m.factory !== null && !m.exists);

	if (unregistered.length === 0) {
		return 0;
	}

	const groups = new Map<string, RegistrationEntry>();

	for (const match of unregistered) {
		const factory = match.factory as UtilityFactory;
		const key = `${factory.name}:${match.parsed.value}`;
		const existing = groups.get(key);

		// Each match represents a distinct class usage (e.g. _hover:margin:sm or _dark:hover:margin:sm).
		// A single modifier is added directly; multiple modifiers from the same class
		// are wrapped as a nested array so they are applied together as a combined variant.
		const modifierEntry: ModifierFactory | ModifierFactory[] | undefined =
			match.modifierFactories.length > 1
				? match.modifierFactories
				: match.modifierFactories[0];

		if (!existing) {
			groups.set(key, {
				factory,
				parsed: match.parsed,
				modifierGroups: modifierEntry ? [modifierEntry] : [],
			});
		} else if (modifierEntry) {
			const entryKey = Array.isArray(modifierEntry)
				? modifierEntry.map((m) => m.key.join(",")).join("|")
				: modifierEntry.key.join(",");
			const isDuplicate = existing.modifierGroups.some((group) => {
				const groupKey = Array.isArray(group)
					? group.map((m) => m.key.join(",")).join("|")
					: group.key.join(",");
				return groupKey === entryKey;
			});

			if (!isDuplicate) {
				existing.modifierGroups.push(modifierEntry);
			}
		}
	}

	let count = 0;

	for (const { factory, parsed, modifierGroups } of groups.values()) {
		const modifierArgs = modifierGroups.length > 0 ? modifierGroups : undefined;

		if (parsed.isArbitrary && parsed.arbitraryValue !== undefined) {
			factory.create({ [parsed.value]: parsed.arbitraryValue }, modifierArgs);
		} else {
			const autoGenerated = factory.autogenerate(`@${parsed.value}`);
			factory.create(autoGenerated, modifierArgs);
		}

		count++;
	}

	return count;
}
