// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
	import type { Styleframe } from "@styleframe/core";

	/** Returns the global styleframe instance from styleframe.config.ts */
	export function styleframe(): Styleframe;

	export const pgTab: (props?: { state?: "inactive" | "active" }) => string;
	export const pgTabList: (props?: Record<string, never>) => string;
	export const pgSplitPane: (props?: Record<string, never>) => string;
	export const pgSplitPanePane: (props?: Record<string, never>) => string;
	export const pgSplitPaneDivider: (props?: Record<string, never>) => string;
	export const pgEditorShell: (props?: Record<string, never>) => string;
	export const pgEditorSurface: (props?: Record<string, never>) => string;
	export const pgErrorBanner: (props?: Record<string, never>) => string;
	export const pgErrorBannerMessage: (props?: Record<string, never>) => string;
	export const pgErrorBannerClose: (props?: Record<string, never>) => string;
	export const pgToolbar: (props?: Record<string, never>) => string;
	export const pgToolbarTitle: (props?: Record<string, never>) => string;
	export const pgToolbarSubtitle: (props?: Record<string, never>) => string;
}

declare module "virtual:styleframe.css" {
	const css: string;
	export default css;
}
