// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
    import type { Styleframe } from "@styleframe/core";

    /** Returns the global styleframe instance from styleframe.config.ts */
    export function styleframe(): Styleframe;

    export const alertRecipe: (props?: { color?: "success" | "warning" | "danger" | "info" }) => string;
    export const avatarRecipe: (props?: { size?: "xs" | "sm" | "md" | "lg" | "xl"; shape?: "circle" | "rounded" | "square" }) => string;
    export const badgeRecipe: (props?: { color?: "primary" | "secondary" | "success" | "warning" | "danger" | "info"; size?: "sm" | "md" | "lg"; variant?: "solid" | "outline" }) => string;
    export const buttonRecipe: (props?: { color?: "primary" | "secondary" | "success" | "danger"; size?: "sm" | "md" | "lg"; variant?: "solid" | "outline" | "ghost"; disabled?: "false" | "true" }) => string;

    export const cardSelector: string;
}

declare module "virtual:styleframe.css" {
    const css: string;
    export default css;
}
