// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
	import type { Styleframe } from "@styleframe/core";

	/** Returns the global styleframe instance from styleframe.config.ts */
	export function styleframe(): Styleframe;

	export const h1: (props?: Record<string, never>) => string;
	export const badge: (props?: Record<string, never>) => string;
	export const buttonRecipe: (props?: Record<string, never>) => string;

	export const badgeSelector: string;
	export const buttonSelector: string;
}

declare module "virtual:styleframe.css" {
	const css: string;
	export default css;
}
