import { test, expect } from "@playwright/test";

test.describe("Utilities Autogenerate Pipeline", () => {
	test.beforeEach(async ({ page }) => {
		await page.goto("/#/utilities-autogenerate");
	});

	test.describe("Scanner-resolved utilities (namespace token resolution)", () => {
		test("margin utility resolves spacing namespace token", async ({
			page,
		}) => {
			const element = page.locator("#test-autogen-margin");
			const margin = await element.evaluate(
				(el) => window.getComputedStyle(el).margin,
			);
			expect(margin).toBe("24px");
		});

		test("padding multiplier generates calc expression", async ({ page }) => {
			const element = page.locator("#test-autogen-padding-mult");
			const padding = await element.evaluate(
				(el) => window.getComputedStyle(el).padding,
			);
			expect(padding).toBe("24px");
		});

		test("background-color resolves via color namespace fallback", async ({
			page,
		}) => {
			const element = page.locator("#test-autogen-bg-color");
			const bg = await element.evaluate(
				(el) => window.getComputedStyle(el).backgroundColor,
			);
			expect(bg).toContain("oklch(");
		});

		test("font-size resolves via font-size namespace", async ({ page }) => {
			const element = page.locator("#test-autogen-font-size");
			const fontSize = await element.evaluate(
				(el) => window.getComputedStyle(el).fontSize,
			);
			expect(fontSize).toBe("24px");
		});

		test("border-radius resolves via border-radius namespace", async ({
			page,
		}) => {
			const element = page.locator("#test-autogen-border-radius");
			const borderRadius = await element.evaluate(
				(el) => window.getComputedStyle(el).borderRadius,
			);
			expect(borderRadius).toBe("9999px");
		});
	});

	test.describe("Array syntax with autogenerate", () => {
		test("@sm resolves to spacing.sm via namespace", async ({ page }) => {
			const element = page.locator("#test-array-sm");
			const padding = await element.evaluate(
				(el) => window.getComputedStyle(el).padding,
			);
			expect(padding).toBe("12px");
		});

		test("@md resolves to spacing.md via namespace", async ({ page }) => {
			const element = page.locator("#test-array-md");
			const padding = await element.evaluate(
				(el) => window.getComputedStyle(el).padding,
			);
			expect(padding).toBe("16px");
		});

		test("@1.5 generates calc multiplier expression", async ({ page }) => {
			const element = page.locator("#test-array-mult");
			const padding = await element.evaluate(
				(el) => window.getComputedStyle(el).padding,
			);
			expect(padding).toBe("24px");
		});

		test("arbitrary value 'auto' is passed through", async ({ page }) => {
			const element = page.locator("#test-array-auto");
			const padding = await element.evaluate(
				(el) => window.getComputedStyle(el).paddingTop,
			);
			// 'auto' is not valid for padding, browser treats as 0px
			expect(padding).toBe("0px");
		});
	});

	test.describe("Combined autogenerated utilities", () => {
		test("multiple scanner-resolved utilities on one element", async ({
			page,
		}) => {
			const element = page.locator("#test-combined-autogen");

			const styles = await element.evaluate((el) => {
				const computed = window.getComputedStyle(el);
				return {
					margin: computed.margin,
					padding: computed.padding,
					backgroundColor: computed.backgroundColor,
					fontSize: computed.fontSize,
					borderRadius: computed.borderRadius,
				};
			});

			expect(styles.margin).toBe("12px");
			expect(styles.padding).toBe("32px");
			expect(styles.backgroundColor).toContain("oklch(");
			expect(styles.fontSize).toBe("18px");
			expect(styles.borderRadius).toBe("4px");
		});
	});
});
