/**
 * Shared constants for the DTS (TypeScript declaration) output pipeline.
 *
 * The DTS pipeline emits three concern-separated files:
 * - `styleframe.d.ts` — top-level exports (the `virtual:styleframe` module shape)
 * - `shims.d.ts`       — ambient shims for non-typed virtual modules (`virtual:styleframe.css`)
 * - `tsconfig.json`    — an extension point wiring `virtual:styleframe` imports to `styleframe.d.ts`
 */

/** Header prepended to every generated declaration file. */
export const DTS_HEADER =
	"// Auto-generated by @styleframe/plugin - DO NOT EDIT";

/** File holding the top-level exports for the `virtual:styleframe` module. */
export const DTS_TYPES_FILENAME = "styleframe.d.ts";

/** File holding ambient shims for non-typed virtual modules. */
export const DTS_SHIMS_FILENAME = "shims.d.ts";

/** File holding the tsconfig extension point. */
export const DTS_TSCONFIG_FILENAME = "tsconfig.json";

/** Specifier for the typed virtual module resolved via tsconfig `paths`. */
export const VIRTUAL_MODULE_ID = "virtual:styleframe";

/** Specifier for the CSS virtual module resolved via the ambient shim. */
export const VIRTUAL_CSS_MODULE_ID = "virtual:styleframe.css";
