/**
 * Shared constants for the DTS (TypeScript declaration) output pipeline.
 *
 * The DTS pipeline emits two concern-separated files:
 * - `styleframe.d.ts` — top-level exports (the `virtual:styleframe` module shape)
 * - `shims.d.ts`       — ambient shims for non-typed virtual modules (`virtual:styleframe.css`)
 *
 * Consumers resolve `virtual:styleframe` by mapping it to `styleframe.d.ts` via
 * a `compilerOptions.paths` entry in their own tsconfig (written by
 * `styleframe init`, or injected by the Nuxt module).
 */

/** Header prepended to every generated declaration file. */
export const DTS_HEADER =
	"// Auto-generated by @styleframe/plugin - DO NOT EDIT";

/** File holding the top-level exports for the `virtual:styleframe` module. */
export const DTS_TYPES_FILENAME = "styleframe.d.ts";

/** File holding ambient shims for non-typed virtual modules. */
export const DTS_SHIMS_FILENAME = "shims.d.ts";

/** Specifier for the CSS virtual module resolved via the ambient shim. */
export const VIRTUAL_CSS_MODULE_ID = "virtual:styleframe.css";
