import type { Root, StyleframeOptions } from "@styleframe/core";
import {
	createRecipeFunction,
	createRoot,
	createUtilityFunction,
} from "@styleframe/core";
import { consume } from "./consume";
import { createRootConsumer } from "./root";

describe("createRootConsumer (dts)", () => {
	let root: Root;
	let recipe: ReturnType<typeof createRecipeFunction>;
	let utility: ReturnType<typeof createUtilityFunction>;

	const consumeRoot = createRootConsumer(consume);
	const options: StyleframeOptions = {};

	beforeEach(() => {
		root = createRoot();
		utility = createUtilityFunction(root, root);
		recipe = createRecipeFunction(root, root);
	});

	it("should emit all recipes when _usage.recipes is empty", () => {
		recipe({ name: "button", base: {}, variants: { size: { sm: {} } } });
		recipe({ name: "card", base: {}, variants: { size: { sm: {} } } });

		const result = consumeRoot(root, options);

		expect(
			result,
		).toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
import type { Styleframe } from "@styleframe/core";

export function styleframe(): Styleframe;

export type ButtonProps = { size?: "sm" };
export const button: (props?: ButtonProps) => string;
export type CardProps = { size?: "sm" };
export const card: (props?: CardProps) => string;
`);
	});

	it("should emit only recipes in _usage.recipes when set is non-empty", () => {
		recipe({ name: "button", base: {}, variants: { size: { sm: {} } } });
		recipe({ name: "card", base: {}, variants: { size: { sm: {} } } });

		root._usage.recipes.add("button");

		const result = consumeRoot(root, options);

		expect(
			result,
		).toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
import type { Styleframe } from "@styleframe/core";

export function styleframe(): Styleframe;

export type ButtonProps = { size?: "sm" };
export const button: (props?: ButtonProps) => string;
`);
	});

	it("should emit exported selectors", () => {
		root.children.push({
			type: "selector",
			id: "sel-1",
			query: ".my-component",
			declarations: {},
			variables: [],
			children: [],
			_exportName: "myComponent",
		});

		const result = consumeRoot(root, options);

		expect(
			result,
		).toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
import type { Styleframe } from "@styleframe/core";

export function styleframe(): Styleframe;

export const myComponent: string;
`);
	});

	it("should return type declarations with no recipe exports when all recipes are filtered", () => {
		recipe({ name: "button", base: {}, variants: { size: { sm: {} } } });

		root._usage.recipes.add("nonexistent");

		const result = consumeRoot(root, options);

		expect(
			result,
		).toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
import type { Styleframe } from "@styleframe/core";

export function styleframe(): Styleframe;
`);
	});
});
