import { generateShims } from "./shims";

describe("generateShims (dts)", () => {
	it("should declare the virtual:styleframe.css module with a string default export", () => {
		expect(
			generateShims(),
		).toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
declare module "virtual:styleframe.css" {
\tconst css: string;
\texport default css;
}
`);
	});

	it("should not declare the typed virtual:styleframe module (resolved via consumer tsconfig paths)", () => {
		expect(generateShims()).not.toContain(
			'declare module "virtual:styleframe"',
		);
	});
});
