import { generateShims } from "./shims";

const TYPES = `// Auto-generated by @styleframe/plugin - DO NOT EDIT
import type { Styleframe } from "@styleframe/core";

export function styleframe(): Styleframe;

export type BadgeProps = { color?: "primary" | "secondary" };
export const badge: (props?: BadgeProps) => string;
`;

describe("generateShims (dts)", () => {
	it("should declare both the ambient virtual:styleframe and virtual:styleframe.css modules", () => {
		expect(generateShims(TYPES))
			.toEqual(`// Auto-generated by @styleframe/plugin - DO NOT EDIT
declare module "virtual:styleframe" {
\timport type { Styleframe } from "@styleframe/core";

\texport function styleframe(): Styleframe;

\texport type BadgeProps = { color?: "primary" | "secondary" };
\texport const badge: (props?: BadgeProps) => string;
}

declare module "virtual:styleframe.css" {
\tconst css: string;
\texport default css;
}
`);
	});

	it("should declare the typed virtual:styleframe module ambiently for zero-config (non-Vue) consumers", () => {
		expect(generateShims(TYPES)).toContain(
			'declare module "virtual:styleframe"',
		);
	});

	it("should emit the auto-generated header exactly once, outside the module blocks", () => {
		const output = generateShims(TYPES);
		const header = "// Auto-generated by @styleframe/plugin - DO NOT EDIT";

		expect(output.split(header).length - 1).toBe(1);
		expect(output.startsWith(`${header}\n`)).toBe(true);
	});

	it("should indent the typed exports one level inside the ambient module", () => {
		expect(generateShims(TYPES)).toContain(
			"\texport const badge: (props?: BadgeProps) => string;",
		);
	});
});
