<template>
	<!-- Scanner-resolved utilities (no explicit values in config) -->
	<div id="test-autogen-margin" class="_margin:lg">Margin LG</div>
	<div id="test-autogen-padding-mult" class="_padding:1.5">Padding 1.5x</div>
	<div id="test-autogen-bg-color" class="_background-color:success">BG Success</div>
	<div id="test-autogen-font-size" class="_font-size:2xl">Font Size 2XL</div>
	<div id="test-autogen-border-radius" class="_border-radius:full">Border Radius Full</div>

	<!-- Explicitly registered via array syntax in config -->
	<div id="test-array-sm" class="_custom-spacing:sm">Custom Spacing SM</div>
	<div id="test-array-md" class="_custom-spacing:md">Custom Spacing MD</div>
	<div id="test-array-mult" class="_custom-spacing:1.5">Custom Spacing 1.5x</div>
	<div id="test-array-auto" class="_custom-spacing:[auto]">Custom Spacing Auto</div>

	<!-- Combined autogenerated -->
	<div
		id="test-combined-autogen"
		class="_margin:sm _padding:xl _background-color:info _font-size:lg _border-radius:md"
	>Combined</div>
</template>
